trigger: none

resources:
  pipelines:
  - pipeline: mypipeline #Arbitraty name to reference
    source: '' #Name of the Infrastructure pipeline that was created
    trigger: true

variables:
- group: 'Infrastructure-Build'
- template: 'deploy-apiWebApp-variables.yml'

stages:
- stage: DEV
  displayName: "DEV Deployment" 
  jobs:
    - template:  ../deploy-webui-api.yml
      parameters:
        environment: ${{ variables.environment }}
        servicePrincipal: '${{ variables.servicePrincipal }}'
        apiAppName: ${{ variables.apiAppName }}
        dockerNamespace: '${{ variables.dockerNamespace }}' 
        dockerRepository: 'referenceApp.api:latest'
        webAppArtifactName: 'web-app-drop'
        webAppSourceLocation: '$(System.DefaultWorkingDirectory)/development_build/**'
        webAppStorageAccount: '${{ variables.webAppStorageAccount }}'
        projectid: '${{ variables.projectid }}'
        buildDefinition: '${{ variables.buildDefinition }}'
