# trigger: none 

# resources: #Step 5: Uncomment lines 1-10 and remove lines 12-17
#   pipelines:
#   - pipeline: mypipeline #Arbitraty name to reference
#     source: 'Infrastructure (run 2nd)' #Name of the Infrastructure pipeline that was created
#     trigger: 
#       branches:
#         include: 
#         - 'main'

resources:
  repositories:
    - repository: self
      type: git  
      ref: refs/heads/main
      trigger: none
    
variables:
- group: 'Infrastructure-Build'
- template: 'deploy-apiWebApp-variables.yml'

stages:
- stage: DEV
  displayName: "DEV Deployment" 
  jobs:
    - template:  ../deploy-webui-api.yml
      parameters:
        environment: ${{ variables.environment }}
        servicePrincipal: '${{ variables.servicePrincipal }}'
        apiAppName: ${{ variables.apiAppName }}
        dockerNamespace: '${{ variables.dockerNamespace }}' 
        dockerRepository: 'referenceApp.api:latest'
        webAppArtifactName: 'web-app-drop'
        webAppSourceLocation: '$(System.DefaultWorkingDirectory)/development_build/**'
        webAppStorageAccount: '${{ variables.webAppStorageAccount }}'
        projectid: '${{ variables.projectid }}'
        buildDefinition: '${{ variables.buildDefinition }}'
