# trigger: none
# 
# resources: #After initial creation, uncomment lines 1-7 and remove lines 9 - 15. This is done to establish automatic triggers
#   pipelines:
#   - pipeline: mypipeline #Arbitraty name to reference
#     source: 'Infrastructure (run 2nd)' #Name of the Infrastructure pipeline that was created
#     trigger: true

resources:
  repositories:
  - repository: self
    type: git
    name: MyProject/MyGitRepo
    trigger: none
    batch: True 
    
variables:
- group: 'Infrastructure-Build'
- template: 'deploy-apiWebApp-variables.yml'

stages:
- stage: DEV
  displayName: "DEV Deployment" 
  jobs:
    - template:  ../deploy-webui-api.yml
      parameters:
        environment: ${{ variables.environment }}
        servicePrincipal: '${{ variables.servicePrincipal }}'
        apiAppName: ${{ variables.apiAppName }}
        dockerNamespace: '${{ variables.dockerNamespace }}' 
        dockerRepository: 'referenceApp.api:latest'
        webAppArtifactName: 'web-app-drop'
        webAppSourceLocation: '$(System.DefaultWorkingDirectory)/development_build/**'
        webAppStorageAccount: '${{ variables.webAppStorageAccount }}'
        projectid: '${{ variables.projectid }}'
        buildDefinition: '${{ variables.buildDefinition }}'
