# HAS NOT BEEN TESTED. POSSIBLE SYNTAX OR PROCESS ISSUES ARE POSSIBLE. 
name: DEV-deploy-apiWebApp (run 3rd)
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
env:
  applicationName: 'app-service-name' #Update to reflect application Name
  apiAppName: 'app-service-name' #place app service Name here
   
jobs:
  BuildTestApi:
    name: Build and Test API
    runs-on: 'windows-latest'
    needs: []
    if: always()
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}  
        
    - name: 'API: Deploy'
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.apiAppName }}
        slot-name: dev
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        images: appsharedcr.azurecr.io/referenceApp.api:latest
        #configuration-file: Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: web-app-drop
        path: "$GITHUB_WORKSPACE"
    - name: Azure Files Upload
      uses: rnakamine/azure-files-upload@v1.0.0
      with:
        connection_string: "${{ secrets.AZURE_STORAGE_ACCOUNT_CS }}"
        source: "$GITHUB_WORKSPACE/development_build/"
        destination: AzureBlob
        # Extra arguments. Can passing flags like `--pattern` or `--destination-path`
        extra_args: --source-container $web --subscription ${{ secrets.SUBSCRIPTION_ID }}
